# Generated by Django 5.0.6 on 2024-08-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='year',
            new_name='meeting_days',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='room',
            name='department',
        ),
        migrations.RemoveField(
            model_name='room',
            name='img',
        ),
        migrations.AddField(
            model_name='room',
            name='academic_year',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(default='Main Building', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='class_capacity',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='room',
            name='class_id',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='room',
            name='names_of_teachers',
            field=models.TextField(default=2023),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_classrooms',
            field=models.TextField(default=2023),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_enrolled_students',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
