# Generated by Django 5.0.6 on 2024-08-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20)),
                ('course_id', models.SmallIntegerField()),
                ('department', models.CharField(max_length=20)),
                ('course_description', models.TextField()),
                ('course_instructor', models.CharField(max_length=28)),
                ('number_of_students', models.PositiveSmallIntegerField()),
                ('grade_level', models.PositiveSmallIntegerField()),
                ('school_term', models.IntegerField()),
                ('assessment_requirements', models.TextField()),
                ('course_trainer_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
