# Generated by Django 5.0.6 on 2024-08-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='class_starting_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
