# Generated by Django 5.0.6 on 2024-08-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(default=2023),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=2023),
        ),
        migrations.AddField(
            model_name='student',
            name='gurdian_name',
            field=models.CharField(default=2023),
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.SmallIntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='student',
            name='student_national_id_number',
            field=models.CharField(default=2023),
        ),
        migrations.AddField(
            model_name='student',
            name='student_next_of_kin',
            field=models.CharField(default=2023),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.SmallIntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(default=2023),
        ),
    ]
